### ISSUE TITLE
Error ketika kena Checkpoint IG

### ISSUE THREAD

**Issue by rakage** [f4devcircle/instagram-starbe#1]
message: '400 - {"message":"challenge_required","challenge":{"url":"https://i.instagram                                    .com/challenge/3543571886/QGvlX0MwZN/","api_path":"/challenge/3543571886/QGvlX0MwZN/","hi                                    de_webview_header":true,"lock":true,"logout":false,"native_flow":true},"status":"fail","e                                    rror_type":"checkpoint_challenge_required"}' }
(node:10291) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getTimeLi                                    neFeed' of undefined
    at getPosts (/var/www/html/ig/app.js:63:35)
    at /var/www/html/ig/app.js:158:8
    at <anonymous>
(node:10291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error or                                    iginated either by throwing inside of an async function without a catch block, or by reje                                    cting a promise which was not handled with .catch(). (rejection id: 3)
(node:10291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. I                                    n the future, promise rejections that are not handled will terminate the Node.js process                                     with a non-zero exit code.

Mohon bantuannya. 
Terima kasih

**Comment by indyka** [comment]
Hai @rakage, hal ini merupakan blokir dari instagramnya, terlihat dari response url challenge yang diberikan oleh api ig.
